-- Feature: UUID native type (MariaDB 10.7+)
--
-- Task: replace CHAR(36) UUID storage with the native UUID type.
-- Problem: CHAR(36) treats UUIDs as plain strings — the database accepts any garbage value
-- without complaining, wastes 36 bytes per row instead of 16, and sorts lexicographically
-- (wrong order for time-based UUIDs, which causes index fragmentation).
--
-- UUID (Universally Unique Identifier) — 128-bit identifier, unique across all machines
-- without any central registry. Standard text form has 32 hex digits split by dashes:
--   550e8400-e29b-41d4-a716-446655440000
-- Before MariaDB 10.7 there was no dedicated type, so UUIDs were stored as CHAR(36).

-- OLD WAY: CHAR(36)
-- The database treats the column as a plain string — it does not know it holds a UUID.
-- Three problems:
--   1. No validation: any 36-character string (or shorter) is accepted without complaint.
--   2. Storage: CHAR(36) always occupies 36 bytes; the actual UUID needs only 16 bytes.
--   3. Sort order: string comparison sorts lexicographically, not by generation time,
--      so index pages fragment as new UUIDs are inserted out of order.
CREATE TABLE IF NOT EXISTS sessions_old (
    id         INT      AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NOT NULL,              -- plain text, no format enforcement
    user_name  VARCHAR(100) NOT NULL
);

INSERT INTO sessions_old (session_id, user_name) VALUES
    ('550e8400-e29b-41d4-a716-446655440000', 'alice'),
    ('6ba7b810-9dad-11d1-80b4-00c04fd430c8', 'bob'),
    ('6ba7b811-9dad-11d1-80b4-00c04fd430c8', 'carol');

INSERT INTO sessions_old (session_id, user_name) VALUES
    ('not-a-uuid-at-all', 'mallory');          -- silently accepted, no error

SELECT id, session_id, user_name FROM sessions_old;

-- NEW WAY: UUID
-- The UUID column type stores the value as 16 bytes internally (binary representation),
-- displays it in the standard dashed text form on SELECT, and rejects malformed values
-- at INSERT time with ERROR 1292.
-- DEFAULT UUID() calls the built-in function that generates a v1 UUID (time-based),
-- so the application does not need to generate or pass UUIDs manually.
CREATE TABLE IF NOT EXISTS sessions_new (
    id         INT  AUTO_INCREMENT PRIMARY KEY,
    session_id UUID NOT NULL DEFAULT UUID(),   -- generated by the database on each INSERT
    user_name  VARCHAR(100) NOT NULL
);

-- only user_name is provided — session_id is filled in automatically via DEFAULT UUID()
INSERT INTO sessions_new (user_name) VALUES ('alice');
INSERT INTO sessions_new (user_name) VALUES ('bob');
INSERT INTO sessions_new (user_name) VALUES ('carol');

SELECT id, session_id, user_name FROM sessions_new;

-- UUID rejects invalid values: INSERT ('not-a-uuid', 'mallory') → ERROR 1292
-- size comparison: UUID stores 16 bytes, CHAR(36) stores 36 bytes — 2.25× larger
SELECT
    16                AS uuid_bytes,
    36                AS char36_bytes,
    ROUND(36 / 16, 2) AS size_ratio;
